-- Auto-generated by scripts/fetch-logos-retry.mjs
-- Run in the Supabase SQL editor.
-- Replaces all existing manufacturers rows.

-- Clear the FK on guides first so the DELETE doesn't violate the constraint.
UPDATE public.guides SET manufacturer_id = NULL;

DELETE FROM public.manufacturers;

INSERT INTO public.manufacturers (name, slug, logo_filename, display_order) VALUES
  ('Land Rover', 'land-rover', 'land-rover.svg', 1),
  ('Jaguar', 'jaguar', 'jaguar.svg', 2),
  ('Rolls-Royce', 'rolls-royce', 'rolls-royce.svg', 3),
  ('Aston Martin', 'aston-martin', 'aston-martin.svg', 4),
  ('McLaren', 'mclaren', 'mclaren.svg', 5),
  ('Mini', 'mini', 'mini.svg', 6),
  ('MG', 'mg', 'mg.svg', 7),
  ('TVR', 'tvr', 'tvr.svg', 8),
  ('Caterham', 'caterham', 'caterham.svg', 9),
  ('BMW', 'bmw', 'bmw.svg', 10),
  ('Mercedes-Benz', 'mercedes-benz', 'mercedes-benz.svg', 11),
  ('Audi', 'audi', 'audi.svg', 12),
  ('Volkswagen', 'volkswagen', 'volkswagen.svg', 13),
  ('Porsche', 'porsche', 'porsche.svg', 14),
  ('Opel', 'opel', 'opel.svg', 15),
  ('Bugatti', 'bugatti', 'bugatti.svg', 16),
  ('Citroën', 'citroen', 'citroen.svg', 17),
  ('DS', 'ds', 'ds.svg', 18),
  ('Peugeot', 'peugeot', 'peugeot.svg', 19),
  ('Renault', 'renault', 'renault.svg', 20),
  ('Alfa Romeo', 'alfa-romeo', 'alfa-romeo.svg', 21),
  ('Ferrari', 'ferrari', 'ferrari.svg', 22),
  ('Fiat', 'fiat', 'fiat.svg', 23),
  ('Lamborghini', 'lamborghini', 'lamborghini.svg', 24),
  ('Lancia', 'lancia', 'lancia.svg', 25),
  ('Koenigsegg', 'koenigsegg', 'koenigsegg.svg', 26),
  ('Volvo', 'volvo', 'volvo.svg', 27),
  ('Acura', 'acura', 'acura.svg', 28),
  ('Daihatsu', 'daihatsu', 'daihatsu.svg', 29),
  ('Honda', 'honda', 'honda.svg', 30),
  ('Infiniti', 'infiniti', 'infiniti.svg', 31),
  ('Lexus', 'lexus', 'lexus.svg', 32),
  ('Mazda', 'mazda', 'mazda.svg', 33),
  ('Mitsubishi', 'mitsubishi', 'mitsubishi.svg', 34),
  ('Nissan', 'nissan', 'nissan.svg', 35),
  ('Subaru', 'subaru', 'subaru.svg', 36),
  ('Suzuki', 'suzuki', 'suzuki.svg', 37),
  ('Toyota', 'toyota', 'toyota.svg', 38),
  ('Dodge', 'dodge', 'dodge.svg', 39),
  ('Ford', 'ford', 'ford.svg', 40),
  ('GMC', 'gmc', 'gmc.svg', 41),
  ('Jeep', 'jeep', 'jeep.svg', 42),
  ('Lincoln', 'lincoln', 'lincoln.svg', 43),
  ('Lucid', 'lucid', 'lucid.svg', 44),
  ('Rivian', 'rivian', 'rivian.svg', 45),
  ('Tesla', 'tesla', 'tesla.svg', 46),
  ('Genesis', 'genesis', 'genesis.svg', 47),
  ('Hyundai', 'hyundai', 'hyundai.svg', 48),
  ('Kia', 'kia', 'kia.svg', 49),
  ('Skoda', 'skoda', 'skoda.svg', 50),
  ('Dacia', 'dacia', 'dacia.svg', 51),
  ('Cupra', 'cupra', 'cupra.svg', 52),
  ('SEAT', 'seat', 'seat.svg', 53),
  ('BYD', 'byd', 'byd.svg', 54),
  ('Geely', 'geely', 'geely.svg', 55),
  ('NIO', 'nio', 'nio.svg', 56),
  ('Xpeng', 'xpeng', 'xpeng.svg', 57);

-- Re-link existing guides to their new manufacturer rows.
UPDATE public.guides
SET manufacturer_id = (SELECT id FROM public.manufacturers WHERE slug = 'land-rover')
WHERE slug = 'range-rover-l322';
